---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates an AWS SNS topic and subscriptions to it'


Parameters:

  DisplayName:
    Description: 'A developer-defined string that can be used to
      identify this SNS topic. Required for SMS subscriptions
      (up to 10 characters long)'
    MaxLength: 10
    Type: String

  TopicName:
    Description: 'Name of the SNS topic'
    Type: String


Resources:

  SnsTopic:
    Properties:
      DisplayName: !Ref DisplayName
      Subscription:
        - Endpoint: raco@gmail.com
          Protocol: email
        - Endpoint: 1-949-555-1212
          Protocol: sms
        # Lambda function to auto-scale batch servers
        # - Endpoint: arn:aws:lambda:us-east-1:123456789012:function:lambda-name
        #   Protocol: lambda
      TopicName: !Ref TopicName
    Type: AWS::SNS::Topic


Outputs:

  TopicArn:
    Description: ARN of the SNS topic
    Export: {'Name': !Sub '${AWS::StackName}-TopicArn'}
    Value: !Ref SnsTopic

  TopicName:
    Description: Name of the SNS topic
    Export: {'Name': !Sub '${AWS::StackName}-TopicName'}
    Value: !GetAtt SnsTopic.TopicName
